name: Windows Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Use the official vcpkg GitHub Action
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: '**/vcpkg.json'

    # Create vcpkg.json for dependencies
    - name: Create vcpkg.json
      run: |
        New-Item -Path . -Name "vcpkg.json" -ItemType "file" -Value @"
        {
          "name": "pixelphys2d",
          "version": "0.1.0",
          "dependencies": [
            "sdl2",
            "glew",
            "opengl"
          ]
        }
        "@
      
    - name: Configure CMake
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        configurePreset: 'ninja-multi-vcpkg'
        buildPreset: 'ninja-multi-vcpkg-release'
        buildPresetAdditionalArgs: "['-DSIMPLIFIED_SKY=ON']"
      
    - name: Create artifacts directory
      run: mkdir -p artifacts
      shell: bash
      
    - name: Package game
      run: |
        mkdir -p artifacts/PixelPhys2D-windows
        
        # Copy executable
        cp build/Release/PixelPhys2D.exe artifacts/PixelPhys2D-windows/ || cp build/bin/Release/PixelPhys2D.exe artifacts/PixelPhys2D-windows/ || echo "Executable not found in expected location"
        
        # Create batch file
        echo '@echo off' > artifacts/PixelPhys2D-windows/run_game.bat
        echo 'echo Starting PixelPhys2D...' >> artifacts/PixelPhys2D-windows/run_game.bat
        echo 'PixelPhys2D.exe' >> artifacts/PixelPhys2D-windows/run_game.bat
        echo 'if ERRORLEVEL 1 pause' >> artifacts/PixelPhys2D-windows/run_game.bat
        
        # Copy DLLs
        cp build/Release/*.dll artifacts/PixelPhys2D-windows/ || cp build/bin/Release/*.dll artifacts/PixelPhys2D-windows/ || echo "No DLLs found in build directory"
        
        # Copy assets (if any)
        mkdir -p artifacts/PixelPhys2D-windows/assets
        cp -r assets/* artifacts/PixelPhys2D-windows/assets/ || echo "No assets found"
        
        # Create README for distribution
        echo "# PixelPhys2D" > artifacts/PixelPhys2D-windows/README.txt
        echo "Run the game by executing run_game.bat" >> artifacts/PixelPhys2D-windows/README.txt
        
        # Create ZIP file
        cd artifacts
        7z a -tzip PixelPhys2D-windows.zip PixelPhys2D-windows
      shell: bash
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PixelPhys2D-windows
        path: artifacts/PixelPhys2D-windows.zip